### ISSUE TITLE
Merging two ASV-tables

### ISSUE THREAD

**Issue by geweaa** [LNUc-EEMiS/compbio-fundamentals#25]
When I merge two ASV tables using:

full_join(seqtab1, seqtab2, by = 'sequence')

It will only recognize two sequences as identical when both have the same length. Is there a way to also include substrings? For example, when sequence A (length 341 bp) and sequence B (length 342 bp) completely overlap, I would like to merge the abundance counts across multiple sequencing runs.

Thank you.

**Comment by erikrikarddaniel** [comment]
No, the join functions need identity. You most likely have a problem in your annotation that needs to be solved. Moreover, it's easier to handle these things with the union() function having the tables in long format.

It's better if you email me questions like this, since it has very little to do with the course itself.
